feat: add basic contents
compio-rs/compio-docs pull request #1
Opened 2024-10-21 19:25 UTC by Berrysoft

I will construct the basic contents here.

2024-10-28 16:22 UTC, George-Miao commented
Can you reformat so that each line is actually in one line? i.e. don't add single new lines. If it's too long for editor to show, you can try enabling line wrap.

2024-10-28 16:24 UTC, Berrysoft commented
I prefer not doing that because, if in the future we need to modify only one word, the whole paragraph would be changed, which makes the diff hard to read.

2024-10-28 16:37 UTC, George-Miao requested changes

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +proactor based IO methods require the ownership of the buffers.
```suggestion
Proactor-based IO functions require the ownership of the buffers, a completely different API idiom from the current ones.
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +Therefore, unless `tokio` finally decided to release 2.0 for the breaking change, it would never use io-uring as first class.
```suggestion
Therefore, unless `tokio` is willing to release 2.0 for the breaking change, io-uring will never be a first class citizen for `tokio`.
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +It's not `tokio`'s fault, because it should keep its API stable.
Delete this line

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +Unfortunately, there was no other runtime, that used io-uring correctly, and was cross-platform.
```suggestion
Let's find an async runtime that uses io-uring correctly and be cross-platform. Unfortunately, there's none.
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +Then I came up with an idea: if there is no such runtime, why cannot I author one?
Don't use first personal POV in docs. Use "Berrysoft" or other name you find appropriate.

```suggestion
That's when Berrysoft came up with the idea: if there is no such runtime, why cannot I author one?
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +I told about the new runtime in the group.
```suggestion
I shared the new runtime to the chat group.
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +When I introduced the runtime in the group, he noticed that and decided to port it to Mac.
```suggestion
When I introduced the runtime in the group, he noticed it and decided to port it to Mac.
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +After his success, the structure of `compio-driver` finally established.
```suggestion
After his success, the structure of `compio-driver` was finally established.
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +Therefore, it should be possible to write a GUI async runtime, in which IO operations in the same thread wouldn't freeze the GUI.
```suggestion
Therefore, it should be possible to write a GUI async runtime, in which IO operations and GUI coexist in one thread without blocking each other.
```

2024-10-28 16:37 UTC, George-Miao commented on src/preface.md
> +I started with another new runtime, copying code from `compio`, and added some other stuffs to handle the message queue on Windows.
```suggestion
I started with another new runtime, copying code from `compio`, and added some other stuff to handle the message queue on Windows.
```

2024-10-28 16:38 UTC, George-Miao commented
> I prefer not doing that because, if in the future we need to modify only one word, the whole paragraph would be changed, which makes the diff hard to read.

It won't. Diff will correctly label out which exact words are being changed. Current line arrangements look ugly in editor.

2024-10-28 16:39 UTC, Berrysoft commented
OK. I'll adjust it, but it takes some time:)

2024-10-28 16:44 UTC, George-Miao commented on src/preface.md
> +It's not `tokio`'s fault, because it should keep its API stable.
Maybe mention a little on how rust's `Future` by-design encourages poll-based API?

2024-11-02 01:00 UTC, George-Miao commented
I have copy all content in this crate to compio-website, should we close this? If there's anything I'd like to fix, I will do it directly there.

2024-11-02 02:19 UTC, Berrysoft commented
OK, closing it now.

2024-11-02 02:20 UTC, closed without merging